# Generated by Django 6.0.5 on 2026-05-07 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_backfill_default_environments'),
        ('software', '0002_softwarerelease_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'baskets',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='baskets_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='BasketSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_entries', to='baskets.basket')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='software.software')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='software.softwareversion')),
            ],
            options={
                'db_table': 'basket_software',
                'unique_together': {('basket', 'software')},
            },
        ),
        migrations.CreateModel(
            name='ServerBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_baskets', to='baskets.basket')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_baskets', to='customers.server')),
            ],
            options={
                'db_table': 'server_baskets',
                'unique_together': {('server', 'basket')},
            },
        ),
        migrations.CreateModel(
            name='ServerInstalledSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='customers.server')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='software.software')),
                ('software_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='software.softwarerelease')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='software.softwareversion')),
            ],
            options={
                'db_table': 'server_installed_software',
                'unique_together': {('server', 'software')},
            },
        ),
    ]
