# Generated by Django 6.0.5 on 2026-05-08 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_backfill_default_environments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('cognito_sub', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSmeOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'db_table': 'staff_sme_organizations',
                'unique_together': {('staff', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='sme_organizations',
            field=models.ManyToManyField(related_name='sme_staff', through='staff.StaffSmeOrganization', to='customers.organization'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('email__isnull', False)), fields=['email'], name='staff_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('cognito_sub__isnull', False), ('deleted_at__isnull', True)), fields=('cognito_sub',), name='staff_cognito_sub_unique'),
        ),
    ]
