# Generated by Django 6.0.5 on 2026-05-08 03:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0002_backfill_installed_from_baskets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchGroup',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patch_groups',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='patch_groups_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='PatchPlan',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patch_plans', to='baskets.basket')),
            ],
            options={
                'db_table': 'patch_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatchPlanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('patch_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='plan_groups', to='patching.patchgroup')),
                ('patch_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_groups', to='patching.patchplan')),
            ],
            options={
                'db_table': 'patch_plan_groups',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PatchGroupStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_num', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('est_time', models.TextField(blank=True, null=True)),
                ('per_server', models.BooleanField(default=False)),
                ('patch_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='patching.patchgroup')),
            ],
            options={
                'db_table': 'patch_group_steps',
                'ordering': ['step_num'],
                'unique_together': {('patch_group', 'step_num')},
            },
        ),
        migrations.AddConstraint(
            model_name='patchplan',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='patch_plans_name_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='patchplangroup',
            unique_together={('patch_plan', 'patch_group')},
        ),
    ]
