# Generated by Django 6.0.5 on 2026-05-08 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_backfill_installed_from_baskets'),
        ('customers', '0004_backfill_default_environments'),
        ('patching', '0001_initial'),
        ('software', '0002_softwarerelease_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchExecution',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='active', max_length=12)),
                ('patch_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='executions', to='baskets.basket')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_executions', to='customers.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_executions', to='customers.organization')),
                ('patch_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='patching.patchplan')),
            ],
            options={
                'db_table': 'patch_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatchExecutionAbort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_num', models.IntegerField()),
                ('attempt_date', models.DateField(blank=True, null=True)),
                ('elapsed', models.TextField(blank=True, null=True)),
                ('steps_completed', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patch_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aborts', to='patching.patchexecution')),
            ],
            options={
                'db_table': 'patch_execution_aborts',
                'ordering': ['attempt_num'],
            },
        ),
        migrations.CreateModel(
            name='PatchExecutionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_num', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('est_time', models.TextField(blank=True, null=True)),
                ('per_server', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('patch_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='patching.patchexecution')),
            ],
            options={
                'db_table': 'patch_execution_steps',
                'ordering': ['step_num'],
            },
        ),
        migrations.CreateModel(
            name='PatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patched_on', models.DateField()),
                ('software_name', models.TextField()),
                ('from_release', models.TextField(blank=True, null=True)),
                ('to_release', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_history', to='customers.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_history', to='customers.organization')),
                ('patch_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='patching.patchexecution')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.software')),
            ],
            options={
                'db_table': 'patch_history',
                'ordering': ['-patched_on', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='patchexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'active')), fields=('organization', 'environment', 'basket'), name='patch_executions_one_active'),
        ),
        migrations.AlterUniqueTogether(
            name='patchexecutionabort',
            unique_together={('patch_execution', 'attempt_num')},
        ),
        migrations.AlterUniqueTogether(
            name='patchexecutionstep',
            unique_together={('patch_execution', 'step_num')},
        ),
        migrations.AddIndex(
            model_name='patchhistory',
            index=models.Index(fields=['organization', 'environment', '-patched_on'], name='patch_histo_organiz_33bf79_idx'),
        ),
    ]
