# Generated by Django 6.0.5 on 2026-05-07 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_org_id', models.TextField()),
                ('jira_name', models.TextField()),
                ('local_name', models.TextField(blank=True, null=True)),
                ('ams_level', models.CharField(blank=True, choices=[('Essential', 'Essential'), ('Enhanced', 'Enhanced'), ('Expert', 'Expert')], max_length=16, null=True)),
                ('zabbix_status', models.CharField(blank=True, choices=[('Good', 'Good'), ('Issue', 'Issue')], max_length=8, null=True)),
                ('help_desk_phone', models.TextField(blank=True, null=True)),
                ('connection_guide_url', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('open_ticket_count', models.IntegerField(blank=True, null=True)),
                ('ticket_count_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_ticket_sync_error', models.TextField(blank=True, null=True)),
                ('jira_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'indexes': [models.Index(condition=models.Q(('ams_level__isnull', False), ('deleted_at__isnull', True)), fields=['ams_level'], name='organizations_ams_level_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('jira_org_id',), name='organizations_jira_org_id_unique')],
            },
        ),
    ]
