# Generated by Django 6.0.5 on 2026-05-07 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_account_id', models.TextField()),
                ('display_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('alerts_enabled', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='customers.organization')),
            ],
            options={
                'db_table': 'org_users',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['organization'], name='org_users_org_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'jira_account_id'), name='org_users_org_jira_account_unique')],
            },
        ),
    ]
