# Generated by Django 6.0.5 on 2026-05-07 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_orguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='customers.organization')),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('cert_expires_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='customers.environment')),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'name'), name='environments_org_name_unique'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(condition=models.Q(('cert_expires_on__isnull', False), ('deleted_at__isnull', True)), fields=['cert_expires_on'], name='servers_cert_idx'),
        ),
        migrations.AddConstraint(
            model_name='server',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('environment', 'name'), name='servers_env_name_unique'),
        ),
    ]
