# Generated by Django 6.0.5 on 2026-05-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_backfill_connection_guide_as_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='connection_guide_url',
        ),
    ]
