# Generated by Django 6.0.5 on 2026-05-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('customers', '0004_backfill_default_environments'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customers.organization'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['scheduled_at'], name='activities_scheduled_idx'),
        ),
    ]
