-- AMS Dashboard — Postgres schema (machine-generated)
--
-- DO NOT EDIT BY HAND. Source of truth is the Django models +
-- migrations under api/<app>/migrations/. Regenerate via:
--
--   docker exec ams-postgres pg_dump --schema-only --no-owner \
--     --no-privileges -U ams ams_dashboard > db/schema.sql
--
-- This file is included in the deploy bundle so the AWS admin can
-- review the schema without reading Django migrations.

--
-- PostgreSQL database dump
--

\restrict 1rqDjZeykJU8Kwt5P1tbKpuCDFTkBpK756t7YaeWQYWajeDWxoUGf1xphVXE0Wg

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activities (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    type character varying(12) NOT NULL,
    priority character varying(8) NOT NULL,
    duration text,
    notes text,
    status character varying(12) NOT NULL,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    assigned_staff_id uuid,
    organization_id uuid
);


--
-- Name: analytic_definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analytic_definitions (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    frequency character varying(12) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    scope character varying(12) NOT NULL
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: basket_software; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.basket_software (
    id bigint NOT NULL,
    basket_id uuid NOT NULL,
    software_id uuid NOT NULL,
    software_version_id uuid NOT NULL
);


--
-- Name: basket_software_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.basket_software ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.basket_software_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: baskets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.baskets (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: customer_analytic_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_analytic_history (
    id uuid NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    value numeric(20,4),
    description text,
    created_at timestamp with time zone NOT NULL,
    customer_analytic_id uuid NOT NULL
);


--
-- Name: customer_analytics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_analytics (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    analytic_definition_id uuid NOT NULL,
    environment_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    server_id uuid
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: environments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.environments (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL
);


--
-- Name: org_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.org_users (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    jira_account_id text NOT NULL,
    display_name text,
    email text,
    role text,
    alerts_enabled boolean NOT NULL,
    is_primary boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organization_id uuid NOT NULL
);


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    jira_org_id text NOT NULL,
    jira_name text NOT NULL,
    local_name text,
    ams_level character varying(16),
    zabbix_status character varying(8),
    help_desk_phone text,
    connection_guide_url text,
    notes text,
    open_ticket_count integer,
    ticket_count_synced_at timestamp with time zone,
    last_ticket_sync_error text,
    jira_synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: patch_execution_aborts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_execution_aborts (
    id uuid NOT NULL,
    attempt_num integer NOT NULL,
    attempt_date date,
    elapsed text,
    steps_completed integer NOT NULL,
    total_steps integer NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    patch_execution_id uuid NOT NULL
);


--
-- Name: patch_execution_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_execution_steps (
    id uuid NOT NULL,
    step_num integer NOT NULL,
    description text NOT NULL,
    est_time text,
    per_server boolean NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    total_time text,
    done boolean NOT NULL,
    patch_execution_id uuid NOT NULL
);


--
-- Name: patch_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_executions (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    status character varying(12) NOT NULL,
    patch_date date,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    total_time text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    basket_id uuid NOT NULL,
    environment_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    patch_plan_id uuid
);


--
-- Name: patch_group_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_group_steps (
    id uuid NOT NULL,
    step_num integer NOT NULL,
    description text NOT NULL,
    est_time text,
    per_server boolean NOT NULL,
    patch_group_id uuid NOT NULL
);


--
-- Name: patch_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_groups (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: patch_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_history (
    id uuid NOT NULL,
    patched_on date NOT NULL,
    software_name text NOT NULL,
    from_release text,
    to_release text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    environment_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    patch_execution_id uuid,
    software_id uuid
);


--
-- Name: patch_plan_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_plan_groups (
    id bigint NOT NULL,
    "position" integer NOT NULL,
    patch_group_id uuid NOT NULL,
    patch_plan_id uuid NOT NULL
);


--
-- Name: patch_plan_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patch_plan_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patch_plan_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patch_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patch_plans (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    basket_id uuid
);


--
-- Name: server_baskets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.server_baskets (
    id bigint NOT NULL,
    basket_id uuid NOT NULL,
    server_id uuid NOT NULL
);


--
-- Name: server_baskets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.server_baskets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.server_baskets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: server_installed_software; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.server_installed_software (
    id bigint NOT NULL,
    recorded_at timestamp with time zone NOT NULL,
    server_id uuid NOT NULL,
    software_id uuid NOT NULL,
    software_release_id uuid,
    software_version_id uuid NOT NULL
);


--
-- Name: server_installed_software_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.server_installed_software ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.server_installed_software_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servers (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    notes text,
    cert_expires_on date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    environment_id uuid NOT NULL
);


--
-- Name: software; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.software (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: software_releases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.software_releases (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    release_name text NOT NULL,
    released_on date,
    "position" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    software_version_id uuid NOT NULL,
    status character varying(12) NOT NULL
);


--
-- Name: software_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.software_versions (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    version text NOT NULL,
    status character varying(12) NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    software_id uuid NOT NULL
);


--
-- Name: staff; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staff (
    deleted_at timestamp with time zone,
    id uuid NOT NULL,
    name text NOT NULL,
    email text,
    phone text,
    cognito_sub text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: staff_sme_organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staff_sme_organizations (
    id bigint NOT NULL,
    organization_id uuid NOT NULL,
    staff_id uuid NOT NULL
);


--
-- Name: staff_sme_organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.staff_sme_organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_sme_organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activities activities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);


--
-- Name: analytic_definitions analytic_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analytic_definitions
    ADD CONSTRAINT analytic_definitions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: basket_software basket_software_basket_id_software_id_7e0b5ebb_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_software
    ADD CONSTRAINT basket_software_basket_id_software_id_7e0b5ebb_uniq UNIQUE (basket_id, software_id);


--
-- Name: basket_software basket_software_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_software
    ADD CONSTRAINT basket_software_pkey PRIMARY KEY (id);


--
-- Name: baskets baskets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.baskets
    ADD CONSTRAINT baskets_pkey PRIMARY KEY (id);


--
-- Name: customer_analytic_history customer_analytic_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_analytic_history
    ADD CONSTRAINT customer_analytic_history_pkey PRIMARY KEY (id);


--
-- Name: customer_analytics customer_analytics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_analytics
    ADD CONSTRAINT customer_analytics_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: environments environments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.environments
    ADD CONSTRAINT environments_pkey PRIMARY KEY (id);


--
-- Name: org_users org_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_users
    ADD CONSTRAINT org_users_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: patch_execution_aborts patch_execution_aborts_patch_execution_id_attem_54c3ca1c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_execution_aborts
    ADD CONSTRAINT patch_execution_aborts_patch_execution_id_attem_54c3ca1c_uniq UNIQUE (patch_execution_id, attempt_num);


--
-- Name: patch_execution_aborts patch_execution_aborts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_execution_aborts
    ADD CONSTRAINT patch_execution_aborts_pkey PRIMARY KEY (id);


--
-- Name: patch_execution_steps patch_execution_steps_patch_execution_id_step_num_9ebeeb13_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_execution_steps
    ADD CONSTRAINT patch_execution_steps_patch_execution_id_step_num_9ebeeb13_uniq UNIQUE (patch_execution_id, step_num);


--
-- Name: patch_execution_steps patch_execution_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_execution_steps
    ADD CONSTRAINT patch_execution_steps_pkey PRIMARY KEY (id);


--
-- Name: patch_executions patch_executions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_executions
    ADD CONSTRAINT patch_executions_pkey PRIMARY KEY (id);


--
-- Name: patch_group_steps patch_group_steps_patch_group_id_step_num_830727ba_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_group_steps
    ADD CONSTRAINT patch_group_steps_patch_group_id_step_num_830727ba_uniq UNIQUE (patch_group_id, step_num);


--
-- Name: patch_group_steps patch_group_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_group_steps
    ADD CONSTRAINT patch_group_steps_pkey PRIMARY KEY (id);


--
-- Name: patch_groups patch_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_groups
    ADD CONSTRAINT patch_groups_pkey PRIMARY KEY (id);


--
-- Name: patch_history patch_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_history
    ADD CONSTRAINT patch_history_pkey PRIMARY KEY (id);


--
-- Name: patch_plan_groups patch_plan_groups_patch_plan_id_patch_group_id_ea0c3240_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_plan_groups
    ADD CONSTRAINT patch_plan_groups_patch_plan_id_patch_group_id_ea0c3240_uniq UNIQUE (patch_plan_id, patch_group_id);


--
-- Name: patch_plan_groups patch_plan_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_plan_groups
    ADD CONSTRAINT patch_plan_groups_pkey PRIMARY KEY (id);


--
-- Name: patch_plans patch_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_plans
    ADD CONSTRAINT patch_plans_pkey PRIMARY KEY (id);


--
-- Name: server_baskets server_baskets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_baskets
    ADD CONSTRAINT server_baskets_pkey PRIMARY KEY (id);


--
-- Name: server_baskets server_baskets_server_id_basket_id_3b5ad5fc_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_baskets
    ADD CONSTRAINT server_baskets_server_id_basket_id_3b5ad5fc_uniq UNIQUE (server_id, basket_id);


--
-- Name: server_installed_software server_installed_software_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_installed_software
    ADD CONSTRAINT server_installed_software_pkey PRIMARY KEY (id);


--
-- Name: server_installed_software server_installed_software_server_id_software_id_c59b1f65_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_installed_software
    ADD CONSTRAINT server_installed_software_server_id_software_id_c59b1f65_uniq UNIQUE (server_id, software_id);


--
-- Name: servers servers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servers
    ADD CONSTRAINT servers_pkey PRIMARY KEY (id);


--
-- Name: software software_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.software
    ADD CONSTRAINT software_pkey PRIMARY KEY (id);


--
-- Name: software_releases software_releases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.software_releases
    ADD CONSTRAINT software_releases_pkey PRIMARY KEY (id);


--
-- Name: software_versions software_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.software_versions
    ADD CONSTRAINT software_versions_pkey PRIMARY KEY (id);


--
-- Name: staff staff_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_pkey PRIMARY KEY (id);


--
-- Name: staff_sme_organizations staff_sme_organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_sme_organizations
    ADD CONSTRAINT staff_sme_organizations_pkey PRIMARY KEY (id);


--
-- Name: staff_sme_organizations staff_sme_organizations_staff_id_organization_id_29d4666f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_sme_organizations
    ADD CONSTRAINT staff_sme_organizations_staff_id_organization_id_29d4666f_uniq UNIQUE (staff_id, organization_id);


--
-- Name: activities_assigned_staff_id_4d91d347; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activities_assigned_staff_id_4d91d347 ON public.activities USING btree (assigned_staff_id);


--
-- Name: activities_organization_id_ebf969e4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activities_organization_id_ebf969e4 ON public.activities USING btree (organization_id);


--
-- Name: activities_scheduled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX activities_scheduled_idx ON public.activities USING btree (scheduled_at);


--
-- Name: analytic_definitions_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX analytic_definitions_name_unique ON public.analytic_definitions USING btree (name) WHERE (deleted_at IS NULL);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: basket_software_basket_id_a5e89612; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX basket_software_basket_id_a5e89612 ON public.basket_software USING btree (basket_id);


--
-- Name: basket_software_software_id_601611aa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX basket_software_software_id_601611aa ON public.basket_software USING btree (software_id);


--
-- Name: basket_software_software_version_id_2d47c48c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX basket_software_software_version_id_2d47c48c ON public.basket_software USING btree (software_version_id);


--
-- Name: baskets_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX baskets_name_unique ON public.baskets USING btree (name) WHERE (deleted_at IS NULL);


--
-- Name: customer_an_custome_4a43f7_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_an_custome_4a43f7_idx ON public.customer_analytic_history USING btree (customer_analytic_id, captured_at DESC);


--
-- Name: customer_analytic_history_customer_analytic_id_1ed74627; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_analytic_history_customer_analytic_id_1ed74627 ON public.customer_analytic_history USING btree (customer_analytic_id);


--
-- Name: customer_analytics_analytic_definition_id_de412f4f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_analytics_analytic_definition_id_de412f4f ON public.customer_analytics USING btree (analytic_definition_id);


--
-- Name: customer_analytics_env_scope_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX customer_analytics_env_scope_unique ON public.customer_analytics USING btree (organization_id, environment_id, analytic_definition_id) WHERE ((deleted_at IS NULL) AND (server_id IS NULL));


--
-- Name: customer_analytics_environment_id_ede7653d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_analytics_environment_id_ede7653d ON public.customer_analytics USING btree (environment_id);


--
-- Name: customer_analytics_organization_id_31839de3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_analytics_organization_id_31839de3 ON public.customer_analytics USING btree (organization_id);


--
-- Name: customer_analytics_server_id_bdbfc5a3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_analytics_server_id_bdbfc5a3 ON public.customer_analytics USING btree (server_id);


--
-- Name: customer_analytics_server_scope_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX customer_analytics_server_scope_unique ON public.customer_analytics USING btree (server_id, analytic_definition_id) WHERE ((deleted_at IS NULL) AND (server_id IS NOT NULL));


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: environments_org_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX environments_org_name_unique ON public.environments USING btree (organization_id, name) WHERE (deleted_at IS NULL);


--
-- Name: environments_organization_id_e6d451f5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX environments_organization_id_e6d451f5 ON public.environments USING btree (organization_id);


--
-- Name: org_users_org_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX org_users_org_idx ON public.org_users USING btree (organization_id) WHERE (deleted_at IS NULL);


--
-- Name: org_users_org_jira_account_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX org_users_org_jira_account_unique ON public.org_users USING btree (organization_id, jira_account_id) WHERE (deleted_at IS NULL);


--
-- Name: org_users_organization_id_b8702f56; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX org_users_organization_id_b8702f56 ON public.org_users USING btree (organization_id);


--
-- Name: organizations_ams_level_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX organizations_ams_level_idx ON public.organizations USING btree (ams_level) WHERE ((ams_level IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: organizations_jira_org_id_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX organizations_jira_org_id_unique ON public.organizations USING btree (jira_org_id) WHERE (deleted_at IS NULL);


--
-- Name: patch_execution_aborts_patch_execution_id_998658d6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_execution_aborts_patch_execution_id_998658d6 ON public.patch_execution_aborts USING btree (patch_execution_id);


--
-- Name: patch_execution_steps_patch_execution_id_7986e2f0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_execution_steps_patch_execution_id_7986e2f0 ON public.patch_execution_steps USING btree (patch_execution_id);


--
-- Name: patch_executions_basket_id_195b18c0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_executions_basket_id_195b18c0 ON public.patch_executions USING btree (basket_id);


--
-- Name: patch_executions_environment_id_b86dc5b7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_executions_environment_id_b86dc5b7 ON public.patch_executions USING btree (environment_id);


--
-- Name: patch_executions_one_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX patch_executions_one_active ON public.patch_executions USING btree (organization_id, environment_id, basket_id) WHERE ((deleted_at IS NULL) AND ((status)::text = 'active'::text));


--
-- Name: patch_executions_organization_id_8dc9e978; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_executions_organization_id_8dc9e978 ON public.patch_executions USING btree (organization_id);


--
-- Name: patch_executions_patch_plan_id_afc413d7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_executions_patch_plan_id_afc413d7 ON public.patch_executions USING btree (patch_plan_id);


--
-- Name: patch_group_steps_patch_group_id_14d28f85; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_group_steps_patch_group_id_14d28f85 ON public.patch_group_steps USING btree (patch_group_id);


--
-- Name: patch_groups_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX patch_groups_name_unique ON public.patch_groups USING btree (name) WHERE (deleted_at IS NULL);


--
-- Name: patch_histo_organiz_33bf79_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_histo_organiz_33bf79_idx ON public.patch_history USING btree (organization_id, environment_id, patched_on DESC);


--
-- Name: patch_history_environment_id_cdf74ed5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_history_environment_id_cdf74ed5 ON public.patch_history USING btree (environment_id);


--
-- Name: patch_history_organization_id_4a54ba65; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_history_organization_id_4a54ba65 ON public.patch_history USING btree (organization_id);


--
-- Name: patch_history_patch_execution_id_6068bdb9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_history_patch_execution_id_6068bdb9 ON public.patch_history USING btree (patch_execution_id);


--
-- Name: patch_history_software_id_4a16c325; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_history_software_id_4a16c325 ON public.patch_history USING btree (software_id);


--
-- Name: patch_plan_groups_patch_group_id_f17cbcf0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_plan_groups_patch_group_id_f17cbcf0 ON public.patch_plan_groups USING btree (patch_group_id);


--
-- Name: patch_plan_groups_patch_plan_id_85bff999; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_plan_groups_patch_plan_id_85bff999 ON public.patch_plan_groups USING btree (patch_plan_id);


--
-- Name: patch_plans_basket_id_13ee6d57; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patch_plans_basket_id_13ee6d57 ON public.patch_plans USING btree (basket_id);


--
-- Name: patch_plans_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX patch_plans_name_unique ON public.patch_plans USING btree (name) WHERE (deleted_at IS NULL);


--
-- Name: server_baskets_basket_id_4336c295; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX server_baskets_basket_id_4336c295 ON public.server_baskets USING btree (basket_id);


--
-- Name: server_baskets_server_id_a167e741; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX server_baskets_server_id_a167e741 ON public.server_baskets USING btree (server_id);


--
-- Name: server_installed_software_server_id_6f09743c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX server_installed_software_server_id_6f09743c ON public.server_installed_software USING btree (server_id);


--
-- Name: server_installed_software_software_id_e483642d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX server_installed_software_software_id_e483642d ON public.server_installed_software USING btree (software_id);


--
-- Name: server_installed_software_software_release_id_13684561; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX server_installed_software_software_release_id_13684561 ON public.server_installed_software USING btree (software_release_id);


--
-- Name: server_installed_software_software_version_id_ef64203c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX server_installed_software_software_version_id_ef64203c ON public.server_installed_software USING btree (software_version_id);


--
-- Name: servers_cert_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX servers_cert_idx ON public.servers USING btree (cert_expires_on) WHERE ((cert_expires_on IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: servers_env_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX servers_env_name_unique ON public.servers USING btree (environment_id, name) WHERE (deleted_at IS NULL);


--
-- Name: servers_environment_id_2d236c5b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX servers_environment_id_2d236c5b ON public.servers USING btree (environment_id);


--
-- Name: software_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX software_name_unique ON public.software USING btree (name) WHERE (deleted_at IS NULL);


--
-- Name: software_releases_one_latest_per_version; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX software_releases_one_latest_per_version ON public.software_releases USING btree (software_version_id) WHERE ((deleted_at IS NULL) AND ((status)::text = 'Latest'::text));


--
-- Name: software_releases_software_version_id_f129c8c7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX software_releases_software_version_id_f129c8c7 ON public.software_releases USING btree (software_version_id);


--
-- Name: software_releases_version_name_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX software_releases_version_name_unique ON public.software_releases USING btree (software_version_id, release_name) WHERE (deleted_at IS NULL);


--
-- Name: software_versions_one_latest; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX software_versions_one_latest ON public.software_versions USING btree (software_id) WHERE ((deleted_at IS NULL) AND ((status)::text = 'Latest'::text));


--
-- Name: software_versions_software_id_ddd785e2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX software_versions_software_id_ddd785e2 ON public.software_versions USING btree (software_id);


--
-- Name: software_versions_software_version_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX software_versions_software_version_unique ON public.software_versions USING btree (software_id, version) WHERE (deleted_at IS NULL);


--
-- Name: staff_cognito_sub_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX staff_cognito_sub_unique ON public.staff USING btree (cognito_sub) WHERE ((cognito_sub IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: staff_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX staff_email_idx ON public.staff USING btree (email) WHERE ((deleted_at IS NULL) AND (email IS NOT NULL));


--
-- Name: staff_sme_organizations_organization_id_1aadea0f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX staff_sme_organizations_organization_id_1aadea0f ON public.staff_sme_organizations USING btree (organization_id);


--
-- Name: staff_sme_organizations_staff_id_277c367e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX staff_sme_organizations_staff_id_277c367e ON public.staff_sme_organizations USING btree (staff_id);


--
-- Name: activities activities_assigned_staff_id_4d91d347_fk_staff_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_assigned_staff_id_4d91d347_fk_staff_id FOREIGN KEY (assigned_staff_id) REFERENCES public.staff(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: activities activities_organization_id_ebf969e4_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_organization_id_ebf969e4_fk_organizations_id FOREIGN KEY (organization_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: basket_software basket_software_basket_id_a5e89612_fk_baskets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_software
    ADD CONSTRAINT basket_software_basket_id_a5e89612_fk_baskets_id FOREIGN KEY (basket_id) REFERENCES public.baskets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: basket_software basket_software_software_id_601611aa_fk_software_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_software
    ADD CONSTRAINT basket_software_software_id_601611aa_fk_software_id FOREIGN KEY (software_id) REFERENCES public.software(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: basket_software basket_software_software_version_id_2d47c48c_fk_software_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.basket_software
    ADD CONSTRAINT basket_software_software_version_id_2d47c48c_fk_software_ FOREIGN KEY (software_version_id) REFERENCES public.software_versions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_analytic_history customer_analytic_hi_customer_analytic_id_1ed74627_fk_customer_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_analytic_history
    ADD CONSTRAINT customer_analytic_hi_customer_analytic_id_1ed74627_fk_customer_ FOREIGN KEY (customer_analytic_id) REFERENCES public.customer_analytics(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_analytics customer_analytics_analytic_definition__de412f4f_fk_analytic_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_analytics
    ADD CONSTRAINT customer_analytics_analytic_definition__de412f4f_fk_analytic_ FOREIGN KEY (analytic_definition_id) REFERENCES public.analytic_definitions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_analytics customer_analytics_environment_id_ede7653d_fk_environments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_analytics
    ADD CONSTRAINT customer_analytics_environment_id_ede7653d_fk_environments_id FOREIGN KEY (environment_id) REFERENCES public.environments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_analytics customer_analytics_organization_id_31839de3_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_analytics
    ADD CONSTRAINT customer_analytics_organization_id_31839de3_fk_organizations_id FOREIGN KEY (organization_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_analytics customer_analytics_server_id_bdbfc5a3_fk_servers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_analytics
    ADD CONSTRAINT customer_analytics_server_id_bdbfc5a3_fk_servers_id FOREIGN KEY (server_id) REFERENCES public.servers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: environments environments_organization_id_e6d451f5_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.environments
    ADD CONSTRAINT environments_organization_id_e6d451f5_fk_organizations_id FOREIGN KEY (organization_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: org_users org_users_organization_id_b8702f56_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.org_users
    ADD CONSTRAINT org_users_organization_id_b8702f56_fk_organizations_id FOREIGN KEY (organization_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_execution_aborts patch_execution_abor_patch_execution_id_998658d6_fk_patch_exe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_execution_aborts
    ADD CONSTRAINT patch_execution_abor_patch_execution_id_998658d6_fk_patch_exe FOREIGN KEY (patch_execution_id) REFERENCES public.patch_executions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_execution_steps patch_execution_step_patch_execution_id_7986e2f0_fk_patch_exe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_execution_steps
    ADD CONSTRAINT patch_execution_step_patch_execution_id_7986e2f0_fk_patch_exe FOREIGN KEY (patch_execution_id) REFERENCES public.patch_executions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_executions patch_executions_basket_id_195b18c0_fk_baskets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_executions
    ADD CONSTRAINT patch_executions_basket_id_195b18c0_fk_baskets_id FOREIGN KEY (basket_id) REFERENCES public.baskets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_executions patch_executions_environment_id_b86dc5b7_fk_environments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_executions
    ADD CONSTRAINT patch_executions_environment_id_b86dc5b7_fk_environments_id FOREIGN KEY (environment_id) REFERENCES public.environments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_executions patch_executions_organization_id_8dc9e978_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_executions
    ADD CONSTRAINT patch_executions_organization_id_8dc9e978_fk_organizations_id FOREIGN KEY (organization_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_executions patch_executions_patch_plan_id_afc413d7_fk_patch_plans_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_executions
    ADD CONSTRAINT patch_executions_patch_plan_id_afc413d7_fk_patch_plans_id FOREIGN KEY (patch_plan_id) REFERENCES public.patch_plans(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_group_steps patch_group_steps_patch_group_id_14d28f85_fk_patch_groups_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_group_steps
    ADD CONSTRAINT patch_group_steps_patch_group_id_14d28f85_fk_patch_groups_id FOREIGN KEY (patch_group_id) REFERENCES public.patch_groups(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_history patch_history_environment_id_cdf74ed5_fk_environments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_history
    ADD CONSTRAINT patch_history_environment_id_cdf74ed5_fk_environments_id FOREIGN KEY (environment_id) REFERENCES public.environments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_history patch_history_organization_id_4a54ba65_fk_organizations_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_history
    ADD CONSTRAINT patch_history_organization_id_4a54ba65_fk_organizations_id FOREIGN KEY (organization_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_history patch_history_patch_execution_id_6068bdb9_fk_patch_exe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_history
    ADD CONSTRAINT patch_history_patch_execution_id_6068bdb9_fk_patch_exe FOREIGN KEY (patch_execution_id) REFERENCES public.patch_executions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_history patch_history_software_id_4a16c325_fk_software_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_history
    ADD CONSTRAINT patch_history_software_id_4a16c325_fk_software_id FOREIGN KEY (software_id) REFERENCES public.software(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_plan_groups patch_plan_groups_patch_group_id_f17cbcf0_fk_patch_groups_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_plan_groups
    ADD CONSTRAINT patch_plan_groups_patch_group_id_f17cbcf0_fk_patch_groups_id FOREIGN KEY (patch_group_id) REFERENCES public.patch_groups(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_plan_groups patch_plan_groups_patch_plan_id_85bff999_fk_patch_plans_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_plan_groups
    ADD CONSTRAINT patch_plan_groups_patch_plan_id_85bff999_fk_patch_plans_id FOREIGN KEY (patch_plan_id) REFERENCES public.patch_plans(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patch_plans patch_plans_basket_id_13ee6d57_fk_baskets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patch_plans
    ADD CONSTRAINT patch_plans_basket_id_13ee6d57_fk_baskets_id FOREIGN KEY (basket_id) REFERENCES public.baskets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: server_baskets server_baskets_basket_id_4336c295_fk_baskets_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_baskets
    ADD CONSTRAINT server_baskets_basket_id_4336c295_fk_baskets_id FOREIGN KEY (basket_id) REFERENCES public.baskets(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: server_baskets server_baskets_server_id_a167e741_fk_servers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_baskets
    ADD CONSTRAINT server_baskets_server_id_a167e741_fk_servers_id FOREIGN KEY (server_id) REFERENCES public.servers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: server_installed_software server_installed_sof_software_release_id_13684561_fk_software_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_installed_software
    ADD CONSTRAINT server_installed_sof_software_release_id_13684561_fk_software_ FOREIGN KEY (software_release_id) REFERENCES public.software_releases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: server_installed_software server_installed_sof_software_version_id_ef64203c_fk_software_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_installed_software
    ADD CONSTRAINT server_installed_sof_software_version_id_ef64203c_fk_software_ FOREIGN KEY (software_version_id) REFERENCES public.software_versions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: server_installed_software server_installed_software_server_id_6f09743c_fk_servers_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_installed_software
    ADD CONSTRAINT server_installed_software_server_id_6f09743c_fk_servers_id FOREIGN KEY (server_id) REFERENCES public.servers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: server_installed_software server_installed_software_software_id_e483642d_fk_software_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.server_installed_software
    ADD CONSTRAINT server_installed_software_software_id_e483642d_fk_software_id FOREIGN KEY (software_id) REFERENCES public.software(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: servers servers_environment_id_2d236c5b_fk_environments_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servers
    ADD CONSTRAINT servers_environment_id_2d236c5b_fk_environments_id FOREIGN KEY (environment_id) REFERENCES public.environments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: software_releases software_releases_software_version_id_f129c8c7_fk_software_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.software_releases
    ADD CONSTRAINT software_releases_software_version_id_f129c8c7_fk_software_ FOREIGN KEY (software_version_id) REFERENCES public.software_versions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: software_versions software_versions_software_id_ddd785e2_fk_software_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.software_versions
    ADD CONSTRAINT software_versions_software_id_ddd785e2_fk_software_id FOREIGN KEY (software_id) REFERENCES public.software(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff_sme_organizations staff_sme_organizati_organization_id_1aadea0f_fk_organizat; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_sme_organizations
    ADD CONSTRAINT staff_sme_organizati_organization_id_1aadea0f_fk_organizat FOREIGN KEY (organization_id) REFERENCES public.organizations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: staff_sme_organizations staff_sme_organizations_staff_id_277c367e_fk_staff_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff_sme_organizations
    ADD CONSTRAINT staff_sme_organizations_staff_id_277c367e_fk_staff_id FOREIGN KEY (staff_id) REFERENCES public.staff(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 1rqDjZeykJU8Kwt5P1tbKpuCDFTkBpK756t7YaeWQYWajeDWxoUGf1xphVXE0Wg

