# Generated by Django 6.0.5 on 2026-05-07 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'software',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='software_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.TextField()),
                ('status', models.CharField(choices=[('Latest', 'Latest'), ('Supported', 'Supported'), ('EOL', 'EOL')], max_length=12)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='software.software')),
            ],
            options={
                'db_table': 'software_versions',
                'ordering': ['position', 'version'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareRelease',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_name', models.TextField()),
                ('released_on', models.DateField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='software.softwareversion')),
            ],
            options={
                'db_table': 'software_releases',
                'ordering': ['position', 'release_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='softwareversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('software', 'version'), name='software_versions_software_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='softwareversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'Latest')), fields=('software',), name='software_versions_one_latest'),
        ),
        migrations.AddConstraint(
            model_name='softwarerelease',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('software_version', 'release_name'), name='software_releases_version_name_unique'),
        ),
    ]
