# Generated by Django 6.0.5 on 2026-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarerelease',
            name='status',
            field=models.CharField(choices=[('Latest', 'Latest'), ('Supported', 'Supported'), ('EOL', 'EOL')], default='Supported', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='softwarerelease',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'Latest')), fields=('software_version',), name='software_releases_one_latest_per_version'),
        ),
    ]
