# Generated by Django 6.0.5 on 2026-05-08 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_backfill_default_environments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticDefinition',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytic_definitions',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='analytic_definitions_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytic',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytic_definition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_assignments', to='analytics.analyticdefinition')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.organization')),
            ],
            options={
                'db_table': 'customer_analytics',
                'ordering': ['analytic_definition__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalyticHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='analytics.customeranalytic')),
            ],
            options={
                'db_table': 'customer_analytic_history',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customeranalytic',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'environment', 'analytic_definition'), name='customer_analytics_org_env_def_unique'),
        ),
        migrations.AddIndex(
            model_name='customeranalytichistory',
            index=models.Index(fields=['customer_analytic', '-captured_at'], name='customer_an_custome_4a43f7_idx'),
        ),
    ]
