# Generated by Django 6.0.5 on 2026-05-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('customers', '0004_backfill_default_environments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customeranalytic',
            name='customer_analytics_org_env_def_unique',
        ),
        migrations.AddField(
            model_name='analyticdefinition',
            name='scope',
            field=models.CharField(choices=[('environment', 'Environment'), ('server', 'Server')], default='environment', max_length=12),
        ),
        migrations.AddField(
            model_name='customeranalytic',
            name='server',
            field=models.ForeignKey(blank=True, help_text="Set when the definition's scope is 'server'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.server'),
        ),
        migrations.AddConstraint(
            model_name='customeranalytic',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('server__isnull', True)), fields=('organization', 'environment', 'analytic_definition'), name='customer_analytics_env_scope_unique'),
        ),
        migrations.AddConstraint(
            model_name='customeranalytic',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('server__isnull', False)), fields=('server', 'analytic_definition'), name='customer_analytics_server_scope_unique'),
        ),
    ]
